---
title: "Datasets"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Datasets

Here we list a few places from which you can access data.

## International and national staitical institutions

These are institutions which do offer access to data.

* [Office of National Statistics (UK)](https://www.ons.gov.uk/)
* [Eurostat](https://ec.europa.eu/eurostat) 
* [U.S Census Bureau](https://www.census.gov/) 
*	[St. Louis FRED Database](https://fred.stlouisfed.org/). A databse maintained by the St. Louis FED with economic and financial data. 
* [INSEE](https://www.insee.fr/fr/accueil) (Ferench Statistics agency) 
* [ECB Statistical DataWarehouse](https://data.ecb.europa.eu/)
* [UK Open data](https://www.data.gov.uk/), UK data portal to various government open data sources
* [Data.gov](https://data.gov/), portal to various US open data sources
* [data.europe.eu](https://data.europa.eu/de), portal to various EU open data sources, US
* [German Open Data Portal](https://www.govdata.de/), portal to various German government open data sources
* [World Bank](https://data.worldbank.org/) has a range of data amongst others a [Inflation data](https://www.worldbank.org/en/research/brief/inflation-database).
* [OECD Database](https://www.oecd.org/en/data.html)
* [International Energy Agency (IEA)](https://www.iea.org/) collects many energy related datasets. Chheck out the "Data" tab to see what is available. To get access you need to register, but that is for free.

## National Surveys

Many nations run large national surveys. This is a selection. Typically summary data are freely available and access to more detailed data can be available for some of these after a registration process.

* [Understanding Society - UK Household Longitudinal Study](https://www.understandingsociety.ac.uk/)
* [National Longitudinal survey(USA)](https://www.bls.gov/nls/) 
* [Socio-Economic Panel, SOEP, Germany](https://www.diw.de/en/diw_01.c.678568.en/research_data_center_soep.html) 
* [IPUMS: census data from different countries](https://www.ipums.org/), 
* [US Census Data](https://www.census.gov/programs-surveys/cps/data.html), 
* [Panel Study of Income Dynamics, PSID, US](https://simba.isr.umich.edu/data/data.aspx)
* [US Survey of Consumer Finances](https://www.federalreserve.gov/econres/scfindex.htm)
* [US American Housing Survey](https://www.census.gov/programs-surveys/ahs/data.html), Mortgage rates, LTV, borrower characteristics

## Aggregator sources

Some organisation provide access to a range of datasets collated from different sources:

* [Consumer Data Research Center](https://data.cdrc.ac.uk/), e.g. Election Data, Residence-Workplace and travel mode data from Census, Council Tax Maps, Index of Multiple Deprivation, Population density
* [The UK Data Service](https://www.ukdataservice.ac.uk/), Census data, International macrodata, Qualitative/mixed methods and UK surveys
*	[Our World in Data](https://ourworldindata.org/), Data Stories with good links to data
* [Data Commons](https://datacommons.org/), a website to facilitate the identification of datasets relevant to your question
*	[Statista](https://www-statista-com.manchester.idm.oclc.org/)} is a website that collates data from a range of different sources and countries. With your university login you may have access to this database.
*	[Economic Data Sources collated by UC Davies](http://cameron.econ.ucdavis.edu/e102/data.html)
* [Economic Data Sources collated by the Economics Network](https://www.economicsnetwork.ac.uk/data_sets)
* [Datasets for published work](https://ejd.econ.mathematik.uni-ulm.de/)
* [Center for International Data](https://cid.ucdavis.edu/), excellent worldwide trade statistics and US tariff data

Not really an aggregator source, but a useful tool when looking for data: [Google dataset serach tool](https://datasetsearch.research.google.com/)

## Journal related datasources

increasingly papers that are published in journals have to make the data (and sometimes codes) used available. Here are a number of places where such links are aggregated.

* [Data related to randomised experiments](https://dataverse.harvard.edu/dataverse/DFEEP), e.g. work by J-PAL and Innovation for  Poverty Action
* [ICPSR](https://www.openicpsr.org/openicpsr/), a database in which publication related data and code is published


## Some Specific Datasets

Here are links to some specific datasets


### UK focused data

*	[UK Police](https://www.police.uk/pu/about-police.uk-crime-data/), All individual crimes reported in the UK
* [Department of Environment and Rural Affairs (DEFRA)](https://uk-air.defra.gov.uk/data/), from here you can get data on air quality in the UK for different locations
* [Summary data on Road Casualty Data in Scotland by council](https://statistics.gov.scot/resource?uri=http%3A%2F%2Fstatistics.gov.scot%2Fdata%2Froad-safety)
* [Department for Transport](https://roadtraffic.dft.gov.uk/downloads), Road traffic data in the UK.
* [Department for Transport](https://www.gov.uk/government/collections/road-accidents-and-safety-statistics), Road accident data. On the basis of these data you can get summaries by different locations and time. 
* [Pedestriansafety.org](http://www.pedestriansafety.org.uk/stats.php)
*	[Land Registry](https://www.gov.uk/government/statistical-data-sets/price-paid-data-downloads), UK House Price data
* [Google Mobility Data](https://www.google.com/covid19/mobility/index.html?hl=en), During the Covid period (2020 to 2022) Google published a mobility index which measured national and regional activities in certain areas (like recreational activities, or shopping areas).
* [Open Data manchester, UK](https://open.manchester.gov.uk/)

### non-UK data

* [Facebook data](https://dataforgood.facebook.com/dfg/tools), a surprisingly rich source of data
* [FRED-MD and FRED-QD](https://research.stlouisfed.org/econ/mccracken/fred-databases/), a standardised set of monthly and quarterly US Macro data which is updated monthly. This is updated by and available from Michael McCracken's website on FRED.
* [Global Carbon Budget Data website](https://globalcarbonbudgetdata.org/), CO2 emission  and emission budget data
* [UTD19](https://utd19.ethz.ch/), traffic data for a range of cities (mainly in Europe).
* [OECD database of hate crimes](https://hatecrime.osce.org/)
* [US Center for Disease Control](https://www.cdc.gov/), Data on all sorts of diseases.
* [F.B.I Crime Data Explorer](https://cde.ucr.cjis.gov/), U.S. Crime data at different levels of aggregation.
* [US Household Surveys](https://usa.ipums.org/usa/), Yearly Big US household survey 2006-onwards
* [US Consumer expenditure survey](https://www.bls.gov/cex/)
* [US Panel Study of Income Dynamics](https://psidonline.isr.umich.edu/), Tracks consumers over time, so can be used to look at career progression, etc.
* [US  Educational Achievements](https://www.nationsreportcard.gov/), Reading and Maths achievement in the US. Data by regions and time.
* [US CDC Wonder Database](https://wonder.cdc.gov/ucd-icd10.html), can help you get detailed disease data by location and time.
* [Home Mortgage Disclosure Act](https://www.consumerfinance.gov/data-research/hmda/historic-data/)
* [Zillow research data](https://www.zillow.com/research/data/), Housing: prices, sales, etc.
* [Realtor.com data](https://www.realtor.com/research/data/), Housing characteristics (costs, physical condition, with household characteristics).
* [Time use surveys, international](https://www.mtusdata.org/mtus/)
* [Federal Financial Institutions Examination Council](https://cdr.ffiec.gov/public/), Panel data on banks' balance sheets.
* [EUROSTAT](https://ec.europa.eu/eurostat/web/income-and-living-conditions/data/database),Income and living conditions in the EU
* [Visual Crossing](https://www.visualcrossing.com/), From here you can get global weather data, including historical data.


# Datasets used on ECLR

Here we provide information on the datasets used on the ECLR page


## mroz dataset ([mroz.csv](https://github.com/datasquad/ECLR/blob/gh-pages/data/Mroz.csv) )

This is a dataset often used in standard econometrics textbooks (such as Wooldridges's Introductory Econometrics). It provides 753 observations for female wages with a range of other variables. You can find details on the variables [here](http://fmwww.bc.edu/ec-p/data/wooldridge/mroz.des). You can get all the datafiles for Wooldridge's book from its publisher [Cengage])https://www.cengage.com/aise/economics/wooldridge_3e_datasets/).


## Major League Baseball ([mlb1.csv](https://github.com/datasquad/ECLR/blob/gh-pages/data/mlb1.csv))

This is another dataset used in Wooldridges's Introductory Econometrics textbook. It has 353 observations for Major League Baseball players in 1993 including their wages and a range of other variables. You can find details on the variables [here](http://fmwww.bc.edu/ec-p/data/wooldridge/mlb1.des). You can get all the datafiles for Wooldridge's book from its publisher [Cengage](https://www.cengage.com/aise/economics/wooldridge_3e_datasets/).


## Greater Manchester accident data ([STATS19_GM_AccData.csv](https://github.com/datasquad/ECLR/blob/gh-pages/data/STATS19_GM_AccData.csv))

In this dataset you can find data on each police-registered road traffic accident in Greater Manchester (UK) between 2010 and 2020. The government provides detailed data on these. The datafile comes from the [Government Data website](https://www.data.gov.uk/dataset/25170a92-0736-4090-baea-bf6add82d118/gm-road-casualty-accidents-full-stats19-data). From this link you can download the latest dataset. The file linked above contains data from 2010 to 2020.

The dataset contains information on more than 40,000 accidents. On each accident there are 25 pieces of information (variables). The data are the coded up information drawn from accident reports. In order to understand how the variables are coded you should have the [Data Dictionary](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/995422/stats19.pdf) at hand.

## Well-Being Dataset ([WBdata.Rdata](https://github.com/datasquad/ECLR/blob/gh-pages/data/WBdata.Rdata))

The data here are prepared from the [European Value Study](https://europeanvaluesstudy.eu/). This is a repeated cross-sectional survey administered across European countries. The study covers a wide range of subjects like attitudes towards work, immigration, family and the environment.

The above dataset is a `Rdata` object which you can load into your Rcode using `load("WBdata.Rdata")`. This will then deliver two objects into your environment. Along the proper datafile (`wb_data`) you will find `wb_data_Des` which contains some information for each of the variables.

