---
title: "List of Examples"
output:
  html_document:
    toc: true
    toc_float: true
---


The following worked examples are implemented on this page. These examples include data and the actual coding.

| Topic | Authors |Concepts | Link |
|:------|:-----|:-----|:--------|
| Climate Change and Natural Disasters | Becker and Zhou | Data import from multiple sources, Basic data analysis, and visualisation | [R-Workthrough](https://datasquad.github.io/ECLR/Ex/DataWalkThrough_ClimateChange.html) | 
| Country-level growth data | Barrow and Lee | Data import from multiple sources | [R-Workthrough](https://datasquad.github.io/ECLR/Ex/DataManagementExample_GrowthData.html) | 
| Minimum Wage | Card and Krueger | Summary Statistics, Diff-in-Diff | [R-Workthrough](https://datasquad.github.io/ECLR/Ex/CardKrueger.html) | 
| Debt Levels and GDP Growth | Reinhard and Rogoff; Herndon, Ash and Pollin | Summary Statistics, Weighting, Hypothesis testing, Regression | [R-Workthrough](https://datasquad.github.io/ECLR/Ex/RogoffReinhard.html) | 
| FRED-MD and Factor models | McCracken and Ng (2016), Bai and Ng (2019) | Data preparation, Factor Model | [R-Workthrough](https://datasquad.github.io/ECLR/Ex/FRED_MD.html) | 
| Firearm Laws and Homicide Deaths | Siegel et al | Data Collection, Diff-in-Diff | R-Workthrough: [Data collection and Prep](https://datasquad.github.io/ECLR/Ex/GunPolicyDataMgmt.html), [Diff-in-Diff analysis](https://datasquad.github.io/ECLR/Ex/GunPolicyDiD.html)
| HAR Models for realized volatility | various, eg. Corsi | Data Handling, Estimating and forecasting from HAR models | [R-Workthrough](https://datasquad.github.io/ECLR/Ex/HAR.html)


The following are commented readings. Interesting papers which are being used to illustrate the econometric aaplication of some methodology. There are no replication data available for these.

| Topic | Authors | Concepts | Link |
|:------|:-----|:-----|:--------|
| Effectiveness of caseworker meetings | [Homrighausen, P. and M. Oberfichtner (2026)](https://www.sciencedirect.com/science/article/pii/S001429212500265X) | IV estimation, randomised control trial | [Discussion](https://datasquad.github.io/ECLR/Ex/Caseworkers.html) |