---
title: "Econom(etr)ic Computing Learning Resource"
output:
  html_document:
    toc: true
    toc_float: true
---

----

# How to learn coding for economists

As an empirical economist you will have to implement statistical techniques. There are many different programmes that can support you in this. Some of these (like STATA) are very specialised to economics. Two very popular programming languages that are used in this field are R and Python.

Learning any programming language can only be done by doing. Here we are not exposing you to a bottom-up introduction of R, but we are immediately exposing you to the exciting possibilities of R and the beauty and excitement of working with real-life data. As we do so we expose you to the basic tools of working with data in R and help you to learn these.

However, you have to accept from the outset that this is going to be a bumby raod! The most crucial skill you will have to embrace and develop is that of finding solutions to problems. You will, as any programmer, yes, even the most experienced ones, search the internet for solutions to your problem. Don't think that you can remember all the important commands from the top of your mind.

# Basic techniques

In the following a few basic data techniques are introduced. Where you need to download csv files you will be guided to a github page from where you can download the respective csv file.

| Topic | Workthrough in R | Workthrough in Python |
|:------|:-----|:-----|
| Installing |  [Video](https://youtu.be/0HzKf-StvOE?si=obnXCLWVP7sIsDy4) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_coding/Py_Install.html)
| First Steps |  [Workthrough in R](https://datasquad.github.io/ECLR/R_FirstSteps.html), [Video](https://youtu.be/fPRcu9g7ZTQ) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_coding/Py_FirstSteps.html)
| Using Packages/Libraries | [Workthrough in R](https://datasquad.github.io/ECLR/R_Packages.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_coding/Py_Libraries.html)
| Loading Data | [Workthrough in R](https://datasquad.github.io/ECLR/R_DataDownload.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_coding/Py_LoadingData.html)
| Basic Data Analysis | [Base R](https://datasquad.github.io/ECLR/R_BasicDataAnalysis.html), [Tidyverse](https://datasquad.github.io/ECLR/R_SummaryStatsTidyverse.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_DataAnalysis/Py_BasicDataAnalysis.html) 
| Basic Data Visualisation (ggplot) | [Workthrough in R](https://datasquad.github.io/ECLR/R_GraphIntro.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_Graphing/Py_GraphIntro.html)
| General coding techniques | [Loops in R](https://datasquad.github.io/ECLR/R_LoopPractice/R_LoopPractice.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_coding/Py_BasicCode.html)

# Regression models and related techniques

| Topic | Workthrough in R | Workthrough in Python |
|:------|:-----|:-----|
| Basic regression models | [Workthrough in R](https://datasquad.github.io/ECLR/R_RegressionIntro.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_Regression/Py_RegressionIntro.html) 
| Predicting from a Regression | [Workthrough in R](https://datasquad.github.io/ECLR/R_RegressionPrediction/R_RegressionPrediction.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_Regression/Py_RegressionPrediction.html) 
| Regression Inference | [Workthrough in R](https://datasquad.github.io/ECLR/R_RegressionInference.html) | 
| IV Regression | [Workthrough in R](https://datasquad.github.io/ECLR/R_RegressionIV.html) | 
| Panel Models | [Workthrough in R](https://datasquad.github.io/ECLR/R_PanelRegression.html) | 

# Large Data / Data Science techniques

| Topic |  Workthrough in R | Workthrough in Python |
|:------|:-----|:-----|
| Regression Model Selection | [Workthrough in R](https://datasquad.github.io/ECLR/R_VariableSelection_Credit/R_VariableSelection_Credit.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_DataScience/Py_VariableSelection_Credit.html)
| Ridge and LASSO Regression | [Workthrough in R](https://datasquad.github.io/ECLR/R_RidgeLasso/R_RidgeLasso.html) | 
| Post Double Selection LASSO | [Workthrough in R](https://datasquad.github.io/ECLR/R_DoubleRobustLasso/R_DoubleRobustLasso.html) | 
| Cross-Validation | [Workthrough in R](https://datasquad.github.io/ECLR/R_CrossValidation/R_CrossValidation.html) | 
| Principal Components | [Workthrough in R](https://datasquad.github.io/ECLR/R_PCA/R_PCA.html) | 

# Dealing with Time-Series variables

| Topic | Workthrough in R | Workthrough in Python |
|:------|:-----|:-----|
| Simulating AR Models | [Workthrough in R](https://datasquad.github.io/ECLR/R_Simulate_AR_processes/R_Simulate_AR_processes.html) | [Workthrough in Py](https://datasquad.github.io/ECLR/Py_TimeSeries/Py_Simulating_AR_Processes.html)
| Unit Root Testing | [Workthrough in R](https://datasquad.github.io/ECLR/R_UnitRootTesting/R_UnitRootTesting.html) | 
| Basic TS modeling | [Workthrough in R](https://datasquad.github.io/ECLR/R_TS_Modelling.html) | 
| GARCH modeling | [Workthrough in R](https://datasquad.github.io/ECLR/R_GarchModelling.html) |  

# Miscallaneous 

These workthroughs demonstrate coding techniques that are useful in a range of different contexts.

| Topic | Workthrough in R | Workthrough in Python |
|:------|:-----|:-----|
| Creating Maps | [Workthrough in R](https://datasquad.github.io/ECLR/R_Mapping/R_Mapping.html) | 
| Law of Large Numbers and Central Limit Theorem | [Workthrough in R](https://datasquad.github.io/ECLR/R_LLN_and_CLT.html) | 
| Monte-Carlo Simulations | [Workthrough in R](https://datasquad.github.io/ECLR/R_MonteCarloSimulations.html) | 

# Examples

In the [Examples section](https://datasquad.github.io/ECLR/examples.html) of this page we collate empirical examples which can be used to help students understand a range of statistical and econometric techniques. This page benefits from a range of empirical examples which have been implemented in a range of books.

- [The Art of Statistics](https://dspiegel29.github.io/ArtofStatistics/) by David Speigelhalter
- [Mastering Metrics](https://www.masteringmetrics.com/) by Joshua Angrist and J&ouml;rn-Steffen Pischke
- [Mostly Harmless Econometrics](https://economics.mit.edu/faculty/angrist/data1/mhe) by Joshua Angrist and J&ouml;rn-Steffen Pischke

The examples from these books and others have been amended or re-written such that students can either use them directly or to facilitate adoption by lecturers.

You can find [further resources here](https://datasquad.github.io/ECLR/resources.html).
