---
title: "Language support"
output:
  html_document:
    fig_width: 1
---

## Support for students with English as a second language

If you come to The University of Manchester, you have accepted that English is your language of study. For a large proportion of students English is, however, not their first language. If you are one of these students then this will pose an additional challenge. [The University of Manchester Language Centre](https://www.languagecentre.manchester.ac.uk/resources/support-and-advice/) offers support which is specifically designed for overseas students. 

In pparticular you should seek out the [super helpful tips](https://www.languagecentre.manchester.ac.uk/resources/support-and-advice/helpsheets-and-worksheets/) on **listening**, **reading**, **speaking** and **writing** in English. It is important to recognise that these skills cannot be taught, but you will have to invest time into applying these skills and the above links offers useful suggestions of what you can do to practice these.

The University of Manchester's Library has also produced the award winning [My Learning Essentials skills programme](https://www.library.manchester.ac.uk/using-the-library/students/training-and-skills-support/my-learning-essentials/). It consists of a combination of short online and in-person workshops which you can access to improve your academic skills. These are designed for all students, not only international students.

## Things to read and listen to for economics students

Interesting economics blogs and podcasts:

* [Econtalk](http://www.econtalk.org/), podcasts on a range of economics issues  
* [FiveThityEight](https://fivethirtyeight.com/economics/), Nate Silver's data-based news service  
* [Freakonomics](http://freakonomics.com/), blogs and podcasts following the pattern set by Steven D. Levitt and Stephen J. Dubner's successful Freakonomics book series   
* [Planet Money](http://planetmoney.com/), this is an Economics programme by National Public radio  
* [Tim Harford](http://timharford.com/) is an Economist at the Financial Times and writes about economics of general interest and also presents the inspirational BBC Radio 4 [More or Less](https://www.bbc.co.uk/programmes/p02nrss1) programme.


Interesting blogs:

* [Diane Coyle](http://www.enlightenmenteconomics.com/blog/), formerly of Manchester, now at The University of Cambridge. She reviews economics books and writes on the digital economy and its measurement.  
* [John H. Cochrane](https://johnhcochrane.blogspot.com/), "news, views, and commentary, from a humorous free-market point of view"  
* [Simon Wren-Lewis](https://mainlymacro.blogspot.com/), left of centre macroeconomist  
* [Marginal Revolution](https://marginalrevolution.com/)  
* [Noah Smith](http://noahpinionblog.blogspot.com/), Economist at Bloomberg


YouTube Channels and Videos:

* [Jacob Clifford](https://www.youtube.com/user/ACDCLeadership), produces videos on textbook level micro- and macroeconomics  
* [One Minute Economics](https://www.youtube.com/channel/UCpsroJwsVKQvRH3ZqdvRetQ), one minute animated clips on a range of economics issues  
* [Ted Ed](https://www.youtube.com/user/TEDEducation), TED talks on a range of interesting isssues  

Twitter:

Under the [#EconTwitter](https://twitter.com/search?q=%23EconTwitter&src=typd) you can find topical discussions on economic topics in the twittersphere. 
