---
title: "Presenting"
output:
  html_document:
    toc: true
    toc_float: true
---

During your degree and even more so afterwards in your workplace you will often be asked to verbally present your thoughts or your work. This can happen in very different environments, a tutorial in which you make a contribution, your study group in which you revise a topic, or a formal presentation where your thoughts are supported by a set of slides.

## In Group Study

This is possibly the most common and also the most relaxed environment in which you will be given the oppportunity to verbally express what you have understood and learned. This are invaluable opportunities to practice your verbal skills. 

In case the language of study (here English) is not your mother tongue, working in groups is a great opportunity to practice your language skills. If at all possible you should have discussions on the topic in English. After all you will be asked to use English in your assessments. Even if it is difficult at first, it is a great way to learn and once you leave University any future employer will expect that you have great English skills.

## In Tutorials

Tutorials are small group meetings. In many of these you will be given the opportunity to make contributions. You should ensure that you use as many of these opportunities as you can. The feedback you will receive on your contributions (from fellow students or the tutor) can significantly contribute t your learning.


## Presentations

Giving a formal presentation can be a really daunting experience. Some of our units ask you to make formal presentations such that you can start making relevant experiences for your later worklife.

### On giving good presentations

*	[Economics Network](https://www.youtube.com/watch?v=7Qtk1J44oGQ) (video, 2:19)  
*	Paul Krugman (Nobel Prize winner) on [Communicating Economics](https://voxeu.org/content/communicating-economics)  
*	Bank of England, [Simple is best: enhancing trust and understanding of central banks through better communication](https://bankunderground.co.uk/2018/11/22/simply-is-best-enhancing-trust-and-understanding-of-central-banks-through-better-communications/)  
*	TED blog, [12 pieces of advice for giving talks that have impact](https://blog.ted.com/12-pieces-of-advice-for-giving-talks-that-have-impact/)  
*	Benjamin Bratton, [We need to talk about TED](https://www.theguardian.com/commentisfree/2013/dec/30/we-need-to-talk-about-ted)  
*	Bob Denham, [5 steps to presenting research](https://www.communicatingeconomics.com/research-video-five-step-outline/)  
*	Bob Denham, [Explain your research in 15 seconds](https://www.communicatingeconomics.com/fifteen-seconds-pitch/)  
*	Bob Denham and Soumaya Keyes, [From economist to journalist](https://www.communicatingeconomics.com/economist-journalist-tips-soumaya-keynes/)  
*	Julian Treasure (9:58) [How to speak so that people want to listen](https://www.youtube.com/watch?v=eIho2S0ZahI)  
*	Lindsay Kolowich, [The science of a great TED talk: what makes a speech go viral](https://blog.hubspot.com/marketing/ted-talk-public-speaking-study)  
*	Paul Edwards, [How to give an academic talk](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-857-network-and-computer-security-spring-2014/projects/MIT6_857S14_proj_umic-talk.pdf)  
*	Visme,  [A Non-Designer s Guide to Creating Memorable Visual Slides](https://online.manchester.ac.uk/bbcswebdav/pid-6753519-dt-content-rid-28143952_1/xid-28143952_1)

### Examples of good talks

*	David Autor (18:38) [Will automation take away all our jobs?](https://www.ted.com/talks/david_autor_why_are_there_still_so_many_jobs?language=en)  
*	Marina Della Giusta (1:10) [Economists and Scientists on Twitter: A Tale of Two Styles?](https://www.youtube.com/watch?v=YUwgP0pucJQ)  
*	Robert Waldinger (12:47) [What makes a good life? lessons from the longest study on happiness](https://www.ted.com/talks/robert_waldinger_what_makes_a_good_life_lessons_from_the_longest_study_on_happiness#t-43155)  
*	[The Royal Economic Society youtube channel](https://www.youtube.com/channel/UCP4yvr6Vd-CW8_e739rJ2-g) has many other talks ranging from 1 minute to 1 hour in length  
*	The [IFS youtube channel](https://www.youtube.com/channel/UCvdfVF9jI_PqV5jtqateNBA) has many talks ranging from 45 seconds to over an hour  
*	[Tim Hartford](http://timharford.com/) does a range of activities that communicate economics, including present the [BBC's radio show More or Less](https://www.bbc.co.uk/programmes/b006qshd/episodes/player). His TED talk [Trial, error and the God complex](https://www.ted.com/talks/tim_harford) is good.


## Visual Aids

You should use visual cues when giving a talk, and not lots of %s

*	Bradford (2004) [Reaching the Visual Learner: Teaching Property Through Art](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=587201) The Law Teacher   
*	Bhutoria, Jerrim and Vignoles (2018) [The financial skills of adults across the world](https://johnjerrim.files.wordpress.com/2018/03/piaac_working_report_march_2018.docx)  

## Graphical representation of data

You should consider not useing pie charts and particularly not tree charts.

*	Healy (2018) [Data Visualization](https://socviz.co/)  
*	Heer and Bostock (2010) [Crowdsourcing graphical perception: using Mechanical Turk to assess visualization design](http://vis.stanford.edu/files/2010-MTurk-CHI.pdf)  
*	Reynolds, Pilling and Marteau (2018) [Communicating quantitative evidence of policy effects](https://www.sciencedirect.com/science/article/pii/S0277953618305276?via%3Dihub), Social Science & Medicine, 218, 1-12  

## Infographics

### On how to make a good infographic

*	Reboot [A beginner's guide to more meaningful infographics](https://reboot.org/2016/03/17/beginners-guide-meaningful-infographics/)  
*	Easelly [CompleteGuideToInfographics](https://online.manchester.ac.uk/bbcswebdav/pid-6753372-dt-content-rid-28142219_1/xid-28142219_1)   
* Easelly [video tutorials](https://www.youtube.com/c/Easellytutorials)  
*	Visme [How to Make an Infographic - A Visual Guide for Beginners](https://online.manchester.ac.uk/bbcswebdav/pid-6753372-dt-content-rid-28142220_1/xid-28142220_1) 

### On the visual and design aspects of infographics

*	Piktochart [8 types of infographics: which is right for you?](https://piktochart.com/blog/8-types-of-infographics-which-right-for-you/)   
*	Canva [40 brilliant and complex topics explained perfectly by infographics](https://www.canva.com/learn/best-infographics/)  
*	The Guardian [How to make infographics: a beginner's guide to data visualisation](https://www.theguardian.com/global-development-professionals-network/2014/aug/28/interactive-infographics-development-data)  
*	The Financial Times [Design secrets behind the FT's best charts of the year](https://www.ft.com/content/4743ce96-e4bf-11e7-97e2-916d4fbac0da)

more about infographics: [infographic journal](https://infographicjournal.com/)

And a funny article on some really rubbish infographics: [16 useless infographics](https://www.theguardian.com/news/datablog/gallery/2013/aug/01/16-useless-infographics), The Guardian; 

