<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Web Exercises</title>

<script src="site_libs/header-attrs-2.28/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="C:/Rcode/packages/webexercises/reports/default/webex.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HOME</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="examples.html">Examples</a>
</li>
<li>
  <a href="Datasets.html">Datasets</a>
</li>
<li>
  <a href="resources.html">Resources</a>
</li>
<li>
  <a href="Author.html">Author</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Web Exercises</h1>

</div>


<div id="introduction-and-data-upload" class="section level1">
<h1>Introduction and Data Upload</h1>
<p>Here we will be using the Women's Wages dataset (mroz) which is made
available <a
href="https://github.com/datasquad/ECLR/blob/gh-pages/data/Mroz.csv">here</a>.
Set your working directory and load data</p>
<p>Let's look at the <code>wage</code> variable (<a
href="http://fmwww.bc.edu/ec-p/data/wooldridge/mroz.des">Variable
Descriptions</a>):</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##       0       2       3       4       5      25     325</code></pre>
<p>In our dataset we have 325 observations that have no wage
information. You will have to be clear what the reason for this is. Are
they not working, or are these genuinely missing observations? The clue
here is in the <code>inlf</code> variable which indicates whether a
particular women is in the labour force (inlf = 1) or not (inlf = 0).
All those observations for which the wage is missing coincide with (inlf
= 0). You can see that from the spreadsheet or by checking</p>
<pre><code>##   [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
##  [38] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
##  [75] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [112] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [149] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [186] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [223] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [260] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
## [297] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</code></pre>
<p>The <code>is.na( )</code> function is a very useful one. It checks
whether the elements in <code>mydata$wage</code> are missing or not. It
returns values of either "TRUE" if they are missing or "FALSE" for
observations where the wage is not missing. When you put this function
into square brackets after <code>mydata$inlf</code> then R will only
return those values of the <code>inlf</code> variable where the
corresponding value for the <code>wage</code> was missing (as this would
produce a "TRUE" from the <code>is.na( )</code> function.)</p>
<p>What we are about to do is the following. We shall first estimate the
following regression model:</p>
<p><span class="math inline">\(wage_i = \alpha_0 + \alpha_1 age_i +
\alpha_2 educ_i + eps_i\)</span></p>
<p>on the basis of all data have wage information. Then, subsequently we
shall use the estimated model to predict the wages of those who are not
currently working. I.e. we'd be answering the question of how much they
should expect to earn (on the basis of their age and education).</p>
<p>Before we do this, there are two reasons of why we should look at
this analysis with a pinch of salt</p>
<ol style="list-style-type: decimal">
<li><p>Including the education variable in such an analysis is likely to
be problematic as it is likely to be correlated with the error terms.
This will produce biased coefficient estimates (an issue you would want
to address for instance vy using an instrumental variables
estimation)</p></li>
<li><p>The reason why the women is not working is most likely not a
random decision and therefore they are not a randomly selected subset.
Therefore it may well be that the relationship we estimated between wage
and the explanatory variables on the basis of those women who do work
may not be the same for women who do not work.</p></li>
</ol>
</div>
<div id="regression-and-prediction" class="section level1">
<h1>Regression and Prediction</h1>
<p>Despite these reservations we shall use this example to demonstrate
how we use R to produce predictions. Let's start by splitting our
dataframe into the two subgroups (those for whom we do have wages and
those for whom we don't). We shall again use the <code>is.na( )</code>
function together with the <code>subset</code> function.</p>
<p>Those observations for which wage is missing go into the
<code>mydata_pred</code> dataframe and all others into
<code>mydata_est</code>.</p>
<p>We now run our regresison on the data in the <code>mydata_est</code>
dataframe</p>
<p>All the results are in <code>lm1</code>. we now use this estimated
model to produce predicted wages for all those observations that are in
<code>mydata_pred</code>. To do this we use the
<code>predict()</code>function. We need to hand in the estimated model
<code>lm1</code> and then the dataframe to which we want to apply the
estimated model to produce forecasts (<code>mydata_pred</code>). This,
of course, requires that this dataframe also has an <code>age</code> and
<code>educ</code> variable as the <code>lm1</code> object will be
looking for these variables.</p>
<p>Check out the new object <code>pr1</code>. It is a vector with 325
predictions for the 325 observations in <code>mydata_pred</code>. You
can add this prediction to the <code>mydata_pred</code> dataframe as a
<code>wagehat</code> variable using
<code>mydata_pred$wagehat &lt;- pr1</code> if that helped you for your
further work.</p>
<div id="new-data" class="section level2">
<h2>New data</h2>
<p>Sometimes you don't have actual observations for which you want to
produce forecast, but rather you have a set of conditioning values at
which you want to calculate predictions. You have to create this set of
<code>age</code> and <code>education</code> combinations yourself. If
there was just an easy way to do that?</p>
<p>This is not a task you are likely to do very often and therefore this
is unlikely to be a memory item. So you should go to your favourite
search engine and search for something like "R create combinations of
two variables". You are likely to find some advice that refers to a
<code>expand.grid</code> function which does appear to offer the
functionality to create a dataframe with all possible combinations of
two (or more) variables. Your next step could be to load the help
function <code>?expand.grid</code>.</p>
<p>It will often be useful to go to the examples in a help function and
there you will find the following example.</p>
<p>Can you adjust this to create all possible combinations of an age
variable that can take any ages between 20 and 55 and an education
variable that takes values, 8, 10, 12 or 14. Save this as a dataframe
called <code>new_df</code> with these two variables. If you have done
this correctly you should get a dataframe with 144 observations and 2
variables</p>
<div class="webex-solution">
<button>
Click here to see the solution
</button>
</div>
<p>Now we will show how you would set this up. You would basically want
to produce a new dataframe which contains, at the least, two variables
named <code>age</code> and <code>educ</code>. You could do this as
follows (try and understand what age/education combinations are being
produced here:</p>
<p>And now we apply the estimated model <code>lm1</code> to this new
dataset.</p>
<p>Of course you could have asked for forecasts for very different
age/education combinations. The <code>predict( )</code> function has a
few extra bells and whistles you could use. You know well (or at least
you should) that when we make predictions using a linear regresison
model we get the conditional expectation, but there wil be uncertainlty
around this expectation. One of the options if the <code>predict</code>
function allows you to get confidence intervals.</p>
<p>Let's try the following:</p>
<p>here we set the confidence <code>level</code> to 0.99 (if you don't
set it explicitly R will use a default of 0.95) and ask R to produce
prediction intervals. Look at the resulting <code>pr3</code> object, it
now has three columns. Let's loook at the 1st row of <code>new_df</code>
and <code>pr3</code></p>
<pre><code>##   age educ
## 1  20    8</code></pre>
<pre><code>##  fit  lwr  upr 
##  1.4 -6.8  9.6</code></pre>
<p>The 1st of our new cases is for someone with age 20 and 8 years of
education. The forecast we produced is 1.40 with lower confidence
interval boundary at -3.82 and the upper boundary at 6.61. So the model
tells us that there is a 99% probability that a women aged 20 with 8
years of education would earn something between -3.82 and 6.61 dollars
per hour. Clearly this is a huge confidence interval and in fact it
reaches into negative hourly wages which don't really make sense. There
are three reasons for this.</p>
<ol style="list-style-type: decimal">
<li>We set a high level of confidence, resulting in a very wide
interval</li>
<li>Our conditioning values were at the lower range of observed ages and
education levels. If we had used conditioning values closer to the
respective averages we would get a narrower interval (try it!)</li>
<li>We asked R to get us an interval for an individual ()by using
<code>interval = "prediction"</code> which means that R also factors is
the observed level of error variance.</li>
</ol>
<p>The last point is important as it allows us to distinguish this from
a slightly different type of confidence interval:</p>
<p>All that has changed is the type of interval we asked for,
<code>interval = "confidence"</code>. Before discussing what the
difference is, let's see how the result changes</p>
<pre><code>##   age educ
## 1  20    8</code></pre>
<pre><code>##    fit    lwr    upr 
##  1.397 -0.056  2.851</code></pre>
<p>We can see that the confidence interval is now much narrower,
although we still have the same expected value of 1.40. The question
this type of interval asks is the following. Assume you have many women
aged 20 and with 8 years of education. What should you expect the
average wage of these many women to be. Answer: With 99% probability,
the model tells us, this value should be between -0.06 and 2.85.</p>
<p>Why does predicting an average produce such a narrower prediction
interval. As you are calculating averages you are averaging out
individual variation and hence we don't need to take that into account.
This tends to massively reduce the width of the confidence interval.</p>
</div>
</div>

<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
