---
title: "Read, Listen & Watch"
output:
  html_document:
    fig_width: 1
---

## Things to read and listen to for economics students {#reading}

Interesting economics blogs and podcasts:

* [Econtalk](http://www.econtalk.org/){target="_blank"}, podcasts on a range of economics issues  
* [FiveThityEight](https://fivethirtyeight.com/economics/){target="_blank"}, Nate Silver's data-based news service  
* [Freakonomics](http://freakonomics.com/){target="_blank"}, blogs and podcasts following the pattern set by Steven D. Levitt and Stephen J. Dubner's successful Freakonomics book series   
* [Planet Money](http://planetmoney.com/){target="_blank"}, this is an Economics programme by National Public radio  
* [Tim Harford](http://timharford.com/){target="_blank"} is an Economist at the Financial Times and writes about economics of general interest and also presents the inspirational BBC Radio 4 [More or Less](https://www.bbc.co.uk/programmes/p02nrss1){target="_blank"} programme.


Interesting blogs:

* [Diane Coyle](http://www.enlightenmenteconomics.com/blog/){target="_blank"}, formerly of Manchester, now at The University of Cambridge. She reviews economics books and writes on the digital economy and its measurement.  
* [John H. Cochrane](https://johnhcochrane.blogspot.com/){target="_blank"}, "news, views, and commentary, from a humorous free-market point of view"  
* [Simon Wren-Lewis](https://mainlymacro.blogspot.com/){target="_blank"}, left of centre macroeconomist 
* [Microeconomic Insights](https://microeconomicinsights.org/){target="_blank"}, a blog which presents current high quality research for public consumption  
* [Marginal Revolution](https://marginalrevolution.com/){target="_blank"}
* [Noah Smith](http://noahpinionblog.blogspot.com/){target="_blank"}, Economist at Bloomberg
* [Nuno Palma](https://nofuturepast.wordpress.com/){target="_blank"}, Economist at University of Manchester blogging on all things Economic History


YouTube Channels and Videos:

* [Jacob Clifford](https://www.youtube.com/user/ACDCLeadership){target="_blank"}, produces videos on textbook level micro- and macroeconomics  
* [One Minute Economics](https://www.youtube.com/channel/UCpsroJwsVKQvRH3ZqdvRetQ){target="_blank"}, one minute animated clips on a range of economics issues  
* [Ted Ed](https://www.youtube.com/user/TEDEducation){target="_blank"}, TED talks on a range of interesting isssues  

Further links to to some Economics themed distractions are provided by the [Economics Network](http://www.studyingeconomics.ac.uk/the-little-bits-we-like/){target="_blank"}.

Twitter:

Under the [#EconTwitter](https://twitter.com/search?q=%23EconTwitter&src=typd){target="_blank"} you can find topical discussions on economic topics in the twittersphere. 
