---
title: "Researching"
output:
  html_document:
    toc: true
    toc_float: true
---

## On planning and structuring

It is good to start with pen and paper to plan the structure of an essay or talk, and take notes

*	Mueller and Oppenheimer (2014) [The Pen is Mightier Than the Keyboard: Advantages of Longhand Over Laptop Note Taking](https://journals-sagepub-com.manchester.idm.oclc.org/doi/abs/10.1177/0956797614524581) Psychological Science  
*	Chatfield (2015) [Why reading and writing on paper can be better for your brain](https://www.theguardian.com/technology/2015/feb/23/reading-writing-on-paper-better-for-brain-concentration), The Guardian  
*	James and Engelhardt (2012) [The effects of handwriting experience on functional brain development in pre-literate children](https://ac-els-cdn-com.manchester.idm.oclc.org/S2211949312000038/1-s2.0-S2211949312000038-main.pdf?_tid=51b09555-c005-4d58-8a11-2e3882d207c5&acdnat=1549801482_911df8fdf04ed64451f15c98ff895b67), Trends in Neuroscience and Education; 


## On finding resources

Often you may need some initial inspiration. You can find a list of interesting reading and podcasts [here](https://datasquad.github.io/EconSkills/language_support.html).

If you are trying to find written material on economic topics you may want to use one or several of the following serach tools:

* [Google](https://www.google.com/), [Bing](https://www.bing.com/), [DuckDuckGo](https://duckduckgo.com/) or any other internet search engine in order to get an overview of the type of available information. But try diffferent combnations of search terms and look beyond the first page. Do not expect high-quality information only.   
* [The University of Manchester Library Search tool](https://www.library.manchester.ac.uk/search-resources/) which will identify catalogued online, journal and book resources. Results will usually have scholarly quality but you may not be able to find extremely recent information.  
* [Google Scholar](https://scholar.google.co.uk/) delivers a subset of results the standard Google search would deliver. It is Google who decides (in a non-public manner) what is scholarly and what isn't. Some journals will not allow its archives to show here. But it is a very useful as it provides much less low quality and irrelevant material compared to a standard Google search.
* Economics Databases: There are a lot of databases with different coverages and different specilisations. A great [overview with links](https://subjects.library.manchester.ac.uk/economic/databases/) is provided by the The University of Manchester Library team.

As you search any of these databases you may have to use complex search strategies to find useful resources. The Uom Library produced this short interactive resource which will introduce you to the [use of search operators in subject databases](https://www.escholar.manchester.ac.uk/learning-objects/mle/search-operators/story_html5.html){target="_blank"}. You will gain a greater understanding of how each operator refines and manipulates your search; enabling you to retrieve more accurate and relevant results.

This [resource](https://www.escholar.manchester.ac.uk/learning-objects/mle/evaluating-sources/story_content/external_files/cheat-sheet.pdf) gives you some guidance to use the context of a publication to judge whether it is reliable, objective and relevant. (UoM, MLE, Library)

## On fact checking and critical reading

This resource explores [how to be critical](https://www.escholar.manchester.ac.uk/learning-objects/mle/being-critical/story_html5.html){target="_blank"}, highlighting practical strategies you can use in your academic reading and writing that will enable you to demonstrate critical analysis in your assignments (UoM Library).

It is your duty to ensure that any facts presented, to the best of the author's knowledge, are correct. This site by the [Economics Network](https://www.economicsnetwork.ac.uk/internet/fact-checking) links to a number of fact checking exercises by news organisations and to resources useful for students having to evaluate the veracity of facts.

## On plagiarism

This is the overarching definition of plagiarism used in [The University of Manchester's Guidance to students on plagiarism](http://documents.manchester.ac.uk/display.aspx?DocID=2870):

> Academic malpractice is any activity – intentional or otherwise – that is likely to undermine the integrity essential to scholarship or research. It includes plagiarism, collusion, fabrication or falsification of results, and anything else that could result in unearned or undeserved credit for those committing it. Academic malpractice can result from a deliberate act of cheating or may be committed unintentionally. 

Plagiarism is a serious issue. We understand that, as students come from a variety of backgrounds, you are unlikely to have a clear understanding of what constitutes plagiarism and what does not. It is therefore extremely important that you read and understand the documentation linked above. The University will assume that you have done so! Ignorance is no excuse as you have all been given programme handbooks which asks you to make yourself familiar with this. If you are in any dout talk to your Academic Advisor.

As a short introduction you may want to look at this YouTube clip produced by the [Hong Kong Baptist University Library](https://youtu.be/Cha331v_vhY) or go thorough this short interactive online resource produced by the UoM Library to [undestand what palgiarism is and techniques to avoid any problems](https://www.escholar.manchester.ac.uk/learning-objects/mle/avoiding-plagiarism/story_html5.html){target="_blank"}.

## On reading and notetaking

You may well have a reading list which is longer than you wish and you neet to learn to read your material efficiently. That means that you may not have to read everything word by word. Sometimes reading the introduction and the conclusion can be enough to decide whetehr you need to read the detail in between. The Economics Network has [some useful advice](http://www.studyingeconomics.ac.uk/tips-for-working-efficiently/effective-reading/){target="_blank"}

Careful notetaking is important, if only to avoid plagiarism. Always make sure that, when you take notes, you

* Note down the source from which your notes come (lectures, textbook, blog, newspaper article, etc)  
* Make sure you know whether your notes are a direct quote or your own paraphrasing.

## On communicating uncertainty

*	Government Statistical Service, [Communicating uncertainty and change](https://gss.civilservice.gov.uk/wp-content/uploads/2018/03/Communicating-uncertainty-and-change-Guidance-for-Official-Statistics-4.pdf)   
*	Manski (2018) [Communicating uncertainty in policy analysis](https://www-pnas-org.manchester.idm.oclc.org/content/early/2018/11/21/1722389115), PNAS   
*	Spiegelhalter, Pearson and Short (2011) [Visualizing Uncertainty About the Future](http://science.sciencemag.org.manchester.idm.oclc.org/content/333/6048/1393), Science, vol 333, issue 6048, 1393-1400;  
*	[Understanding Uncertainty](https://understandinguncertainty.org/blog), of the Winton programme for the public understanding of risk at the University of Cambridge  

## On designing good visual aids

* [A Non-Designer's Guide to Creating Memorable Visual Slides](https://online.manchester.ac.uk/bbcswebdav/pid-6751652-dt-content-rid-28686073_1/xid-28686073_1), Visme.pdf  
*	[Design secrets behind the FT’s best charts of the year](https://online.manchester.ac.uk/bbcswebdav/pid-6751652-dt-content-rid-28686074_1/xid-28686074_1), Financial Times 
