---
title: "Writing"
output:
  html_document:
    toc: true
    toc_float: true
---

## On writing generally

* Understand your task: Whether you have to answer a question in an exam or have to produce a piece of coursework you need to ensure that you understand what your task is. The UoM has produced a [list of instruction words](https://www.escholar.manchester.ac.uk/learning-objects/mle/understanding-task/story_content/external_files/instruction-words.pdf){target="_blank"} and you should ensure you understand what you are to do. This is part of a short online resource by the UoM Library which takes you through the [process of analysing your assignment task](https://www.escholar.manchester.ac.uk/learning-objects/mle/understanding-task/story_html5.html){target="_blank"} to ensure that you're clear about what you're being asked to do, giving you some useful techniques to ensure that your work remains focused on directly addressing the question at hand.  
*	It helps to structure your process of researching and writing and this source could give you some ideas: [Planning and storyboards](https://cunyhumanitiesalliance.org/researchpaperfa17/2017/10/09/paper-sketch-storyboard-2/){target="_blank"}  
* As you write your piece you need to help the reader to see a structure in your argument. One way in which you do that is by organising your thoughts in paragraphs. These are two sources which will helo you understand how to construct paragraphs: [The secrets of good paragraph writing](https://www.time4writing.com/writing-resources/paragraph-writing-secrets/){target="_blank"} and	[Basic paragraph structure](https://learn.lexiconic.net/para2.htm){target="_blank"}


## On writing in economics

*	Schmeiser (2017) [Teaching writing in economics](https://www.tandfonline.com/doi/pdf/10.1080/00220485.2017.1353459?needAccess=true)  
*	Neugeboren and Jacobson (2005) [Writing economics](https://writingproject.fas.harvard.edu/files/hwp/files/writingeconomics.pdf) aimed at sophmore Harvard undergrads  
*	Dudenhefer (2009) [A guide to writing in economics](http://writing.ku.edu/sites/writing.drupal.ku.edu/files/docs/Guide_Writing_Economics.pdf), Duke University  

## On referencing and plagiarism

This [online resource](https://www.escholar.manchester.ac.uk/learning-objects/mle/introducing-referencing/story_html5.html) explores the principles behind referencing, highlighting why it is good academic practice. It outlines when and how you need to reference, and how to read a reference when following up a source listed on a reading list or bibliography. (UoM, Learning Essentials)

Here we use the Harvard referencing style and all your referencing should adhere to this [guidance](http://subjects.library.manchester.ac.uk/referencing/referencing-harvard). (UoM)

The University of Manchester provides a range of [resources for referencing](http://subjects.library.manchester.ac.uk/referencing).

If you do not reference properly you can easily fall foul of University's plagiarism rules. It is vital that you understand the regulations. You may want to go through this short online resource produced by the UoM Library to [undestand what palgiarism is and techniques to avoid any problems](https://www.escholar.manchester.ac.uk/learning-objects/mle/avoiding-plagiarism/story_html5.html){target="_blank"}.

## On writing an essay

Here are things to look out of you write an essay.

* This UoM Library resource outlines a five-step technique you can use to help you to [identify your main arguments](https://www.escholar.manchester.ac.uk/learning-objects/mle/developing-argument/story_html5.html){target="_blank"}, and to organise your ideas into a coherent structure.


## On writing a policy brief

*	[Tips for writing economics essays](https://www.economicshelp.org/help/tips-economic-essays/){target="_blank"}, Economics.help  
*	[How to write a policy brief](https://www.parliament.uk/mps-lords-and-offices/offices/bicameral/post/about-post/writing-a-policy-brief/){target="_blank"}, UK Parliament   
*	[How to write a policy brief](https://www.wikihow.com/Write-a-Policy-Brief){target="_blank"}, WikiHow  
*	[Guidelines for writing a policy brief](https://www.pep-net.org/sites/pep-net.org/files/typo3doc/pdf/CBMS_country_proj_profiles/Philippines/CBMS_forms/Guidelines_for_Writing_a_Policy_Brief.pdf){target="_blank"}, Community-Based Monitoring System  
*	[Policy briefs: a guide to writing policy briefs for research uptake](http://blogs.lshtm.ac.uk/griphealth/files/2017/01/Policy-briefs-guide_2015.pdf){target="_blank"}, Resilient and Responsive Health Systems   
*	[How to write a policy brief](https://www.idrc.ca/sites/default/files/idrcpolicybrieftoolkit.pdf){target="_blank"}, International Development Research Centre  
*	[How to plan, write and communicate an effective policy brief](https://www.researchtoaction.org/wp-content/uploads/2014/10/PBWeekLauraFCfinal.pdf){target="_blank"}, Research to Action   
*	[Writing a policy brief](https://writingcenter.unc.edu/policy-briefs/), University of North Carolina at Chapel Hill  
*	[Food Security Communications Toolkit](http://www.fao.org/3/i2195e/i2195e00.htm){target="_blank"}, FAO  
*	[Writing policy briefs](http://www.fao.org/3/i2195e/i2195e03.pdf){target="_blank"}, FAO  


## Dissertation

A dissertation is a substantial piece of work and requires careful planning from finding a topic to the final [proof read](#Proofreading). This [site by the Economics Network](http://www.studyingeconomics.ac.uk/dissertation/){target="_blank"} guides you through many of the important steps.

## Proofreading{#Proofreading}

You finished writing your work? Think again. This resource by the UoM Library explores three vital elements to proofreading your work - flow, clarity and accuracy - and gives you a chance to learn about and apply some techniques to [ensure that you check your work properly](https://www.escholar.manchester.ac.uk/learning-objects/mle/proofreading/story_html5.html){target="_blank"}.

## How will your work be assessed?

Here at The University of Manchester's Economics Department we have bespoke assessment criteria ([for undergraduate students](docs/EconomicsUndergraduateAssessmentCriteria.pdf){target="_blank"} and for [Masters students](docs/EconomicsPostgraduateAssessmentCriteria.pdf){target="_blank"}). These may sound rather generic at the writing stage, but when you read through your or someone else's work you should practice finding elements of the respective grade categories in the work.